### ISSUE TITLE
Support JSX

### ISSUE THREAD

**Issue by xiaohai-huang** [unity-atoms/fiber#17]
This package looks similar to react as a UI library. Can I write components using jsx and use hooks like `useState` and `useEffect`?

**Comment by AdamRamberg** [comment]
Sorry for the very late reply. You are correct in that it's very similar to React. Both React and Solid.js were big inspirations for this library. You can't write jsx, but you have signals that acts like `useState` and effects that works like `useEffect`. Muteable signals can be created like this `new Signal(...)`, while computed / derived can be created using `F.CreateComputedSignal`. Effects can be created by calling `F.CreateEffect`. 

Be aware though that you will need to dig into the code base quite a lot to get started, since I haven't had the time to create proper documentation. If you find it compelling I would suggest you to clone the repo and try out the docs example.
